# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a81f0a76421ca73b7f31904219eb043a82edf49897224946de06fe330fd9545eb78aad8adadfbdbe6cc5a01416b617dd88c30874fe7960545db996396ad8d26d

test:
  secret_key_base: e4414dd7ee2c17ce534bf0da53deec4398b6682e5d13ee979f0b23abac8b149310d65ca2be64eabb7cdbf3e3660c63b64b0cd2bd40c7b53fc02e59ccb020f9a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
